version: '3'
services:
    web:
        build: .
        ports:
            - "5000:5000"
        volumes:
            - .:/var/www/app
        depends_on:
            - redis
    redis:
        image: redis
    