version: '2'
services:
    service:
        build: ./service
        ports:
            - "80:80"
            - "80"
        container_name: 'service'
        volumes:
            - ./service:/var/www/app
        depends_on:
            - redis
    redis:
        image: redis
    web:
        build: ./web
        ports:
            - "50:50"
        container_name: 'web'
        volumes:
            - ./web:/home/app
        depends_on:
            - pdf
            - redis
    pdf:
        build: ./pdf
        container_name: 'pdf'
        ports:
            - "5000"
            - "5000:5000"
        volumes:
            - ./pdf:/code

    
