version: '2'
services:
    web:
        build: ./web
        ports:
            - "5000:5000"
        volumes:
            - .:/home/app
        depends_on:
            - redis
            - pdf
    redis:
        image: redis
    
    pdf:
        build: ./pdf
        ports:
            - 5000:5000
        volumes:
            - .:/code